---
# ------
# Model configuration for MUSK
# ------

d_instance: 166
n_classes: 2
n_expec_dims: 2

EmbeddingSpaceNN:
  Encoder:
    type: flat
    d_in: ${d_instance}
    ds_hid: [128]
    d_out: 256
    dropout: ${EmbeddingSpaceNN.TrainParams.dropout}
  Aggregator:
    d_in: ${EmbeddingSpaceNN.Encoder.d_out}
    ds_hid: []
    n_classes: ${n_classes}
    dropout: ${EmbeddingSpaceNN.TrainParams.dropout}
    agg_func_name: max
  TrainParams:
    lr: 1e-3
    wd: 1e-3
    dropout: 0.25

InstanceSpaceNN:
  Encoder:
    type: flat
    d_in: ${d_instance}
    ds_hid: []
    d_out: 512
    dropout: ${InstanceSpaceNN.TrainParams.dropout}
  Aggregator:
    d_in: ${InstanceSpaceNN.Encoder.d_out}
    ds_hid: [256, 64]
    n_classes: ${n_classes}
    dropout: ${InstanceSpaceNN.TrainParams.dropout}
    agg_func_name: mean
  TrainParams:
    lr: 5e-4
    wd: 1e-5
    dropout: 0.45

AttentionNN:
  Encoder:
    type: flat
    d_in: ${d_instance}
    ds_hid: [128, 256]
    d_out: 128
    dropout: ${AttentionNN.TrainParams.dropout}
  Aggregator:
    n_heads: 1
    d_in: ${AttentionNN.Encoder.d_out}
    ds_hid: []
    d_attn: 256
    n_classes: ${n_classes}
    dropout: ${AttentionNN.TrainParams.dropout}
  TrainParams:
    lr: 1e-3
    wd: 1e-5
    dropout: 0.15

ClusterGNN:
  Encoder:
    type: flat
    d_in: ${d_instance}
    ds_hid: []
    d_out: 128
    dropout: ${ClusterGNN.TrainParams.dropout}
  GNN:
    d_enc: ${ClusterGNN.Encoder.d_out}
    d_gnn: 64
    ds_gnn_hid: [128, 256]
    ds_fc_hid: [128]
  TrainParams:
    lr: 5e-4
    wd: 1e-5
    dropout: 0.2
